labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: question
    color: d876e3
    description: Further information is requested
  - name: "priority: high"
    color: b60205
    description: Must be fixed/addressed immediately
  - name: "priority: medium"
    color: eb6420
    description: Important but non-critical
  - name: "priority: low"
    color: 1d76db
    description: Nice-to-have, little impact
  - name: "in progress"
    color: 0052cc
    description: Work has started
  - name: awaiting feedback
    color: fbca04
    description: Needs more info from OP or stakeholders
  - name: blocked
    color: d4c5f9
    description: Can't proceed until another issue is resolved
  - name: help wanted
    color: 008672
    description: Looking for outside contributors
  - name: good first issue
    color: 7057ff
    description: Simple task for newcomers
  - name: duplicate
    color: cfd3d7
    description: This issue is a duplicate of another
  - name: invalid
    color: e4e669
    description: Not a bug or feature, or can't be reproduced
  - name: wontfix
    color: ffffff
    description: Issue acknowledged but won't be addressed